config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/index', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/pricing', to: 'pages#pricing'
  get '/payment', to: 'pages#payment'
  post '/checkout', to: 'pages#checkout'

  #API
  namespace :api do
    namespace :v2 do
      resources :boards, only: %i[index]
    end
  end

  #Origin
  resources :favorites, only: %i[index]

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: %i[create]
    end

    member do
      post :favorite
      put :hide
    end
  end

  # shallow =>
  # resources :boards do
  #   resources :posts, only: [:index, :new, :create]
  # end
  # resources :posts, except: [:index, :new, :create]

  resources :users, only: %i[create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/frontend/_footer.html.erb
<footer class="fixed-bottom text-center">
  PPT版權所有
</footer>

app/views/shared/frontend/_navbar.html.erb
<div class="header d-flex justify-content-between px-2">
  <span>
    <主功能表>
  </span>
  <span class="title">
    <%= link_to  "批踢踢實業坊", root_path %>
  </span>
  <span>
    <nav>
      <ul>
        <% if current_user  %>
        <li>
          <%= current_user.account %>
        </li>  
        <li>
            <%= link_to '登出', sign_out_users_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to '登入', sign_in_users_path %>
          </li>
          <li>
            <%= link_to '註冊', sign_up_users_path %>
          </li>
        <% end %>
      </ul>
    </nav>
</div>