config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/index', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/pricing', to: 'pages#pricing'
  get '/payment', to: 'pages#payment'
  post '/checkout', to: 'pages#checkout'

  #API
  namespace :api do
    namespace :v2 do
      resources :boards, only: %i[index]
    end
  end

  #Origin
  resources :favorites, only: %i[index]

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: %i[create]
    end

    member do
      post :favorite
      put :hide
    end
  end

  # shallow =>
  # resources :boards do
  #   resources :posts, only: [:index, :new, :create]
  # end
  # resources :posts, except: [:index, :new, :create]

  resources :users, only: %i[create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/pages/_link.html.erb
<div class="link d-flex">
  <%= link_to link, class: "w-100 d-flex justify-content-between" do %>
    <span>
      <%= name.capitalize.insert(0, "(").insert(2, ")")  %>
    </span>
    <span>
      <%= "【#{t("pages.#{name}")}】" %>
    </span>
  <% end %>
</div>

app/views/pages/about.html.erb
<h1>關於我們</h1>

app/views/pages/index.html.erb
<div id="app">
  <App></App>
</div>

<div class="leave_message px-2">
  <div class="page-pic py-3">
    <img src="https://picsum.photos/1200/200/?random=1" class="w-100">
  </div>

  <p class="content">
    <span>
      辦公室是啊，走勢當初消費對此都是國語引進描述，女兒徹底呵呵。
    </span>
  </p>

  <p class="warning d-flex text-center align-items-center">
    上方為使用者心情點播留言區，不代表本站立場
  </p>
</div>

<div class="container">
  <div class="row">
    <div class="col-9 col-md-5 mx-auto">
      <div class="link-group">
        <%= render "link", name: "announce", link: "boards" %>
        <%= render "link", name: "favorites", link: favorites_path %>
        <%= render "link", name: "class", link: "boards" %>
        <%= render "link", name: "mail", link: "boards" %>
        <%= render "link", name: "talk", link: "boards" %>
        <%= render "link", name: "user", link: "boards" %>
        <%= render "link", name: "xyz", link: "boards" %>
        <%= render "link", name: "play", link: "boards" %>
        <%= render "link", name: "namelist", link: "boards" %>
        <%= render "link", name: "goodbye", link: sign_out_users_path %>
      </div>
    </div>
  </div>
</div>

  

app/views/pages/payment.html.erb
<h1>方案 <%= @plan.upcase %></h1>
<h2>價錢 <%= @price %></h2>

<script src="https://js.braintreegateway.com/web/dropin/1.23.0/js/dropin.min.js"></script>

<%= form_with(url: "/checkout?plan=#{@plan}", id: 'payment_form', method: 'post', local: true) do %>
  <div id="dropin-container"></div>
  <button id="submit-button">付款</button>
  <input type="hidden" value="" id="nonce" name="nonce">
<% end %>

<script>
  var button = document.querySelector('#submit-button');

  braintree.dropin.create({
    authorization: '<%= @token %>',
    container: '#dropin-container'
  }, function (createErr, instance) {
    button.addEventListener('click', function (e) {
      e.preventDefault();

      instance.requestPaymentMethod(function (err, payload) {
        const nonce_dom = document.querySelector('#nonce');
        const form = document.querySelector('#payment_form');
        nonce_dom.value = payload.nonce;
        form.submit();
      });
    });
  });
</script>

app/views/pages/pricing.html.erb
<h1>課金啦！</h1>
<ul>
  <li>
    <%= link_to "Plan A(#{ENV['plan_a_price']} 元)", payment_path(plan: 'a') %>
  </li>
  <li>
    <%= link_to "Plan B(#{ENV['plan_b_price']} 元)", payment_path(plan: 'b') %>
  </li>
</ul>