config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/index', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/pricing', to: 'pages#pricing'
  get '/payment', to: 'pages#payment'
  post '/checkout', to: 'pages#checkout'

  #API
  namespace :api do
    namespace :v2 do
      resources :boards, only: %i[index]
    end
  end

  #Origin
  resources :favorites, only: %i[index]

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: %i[create]
    end

    member do
      post :favorite
      put :hide
    end
  end

  # shallow =>
  # resources :boards do
  #   resources :posts, only: [:index, :new, :create]
  # end
  # resources :posts, except: [:index, :new, :create]

  resources :users, only: %i[create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/board.rb
class Board < ApplicationRecord
  acts_as_paranoid
  validates :title, presence: true

  has_many :posts, dependent: :destroy
  has_many :board_masters
  has_many :users, through: :board_masters

  has_many :favorite_boards
  has_many :favorited_users, through: :favorite_boards, source: :user

  def favorited_by?(user)
    favorited_users.include?(user)
  end

  include AASM

  aasm(column: 'state') do
    # default column: aasm_state
    state :normal, initial: true
    state :hidden, :locked

    event :hide do
      transitions from: %i[normal locked], to: :hidden
    end

    event :show do
      transitions from: :hidden, to: :locked
    end

    event :lock do
      transitions from: %i[normal hidden], to: :locked

      after_transaction { puts '已鎖版！' }
    end

    event :unlock do
      transitions from: :locked, to: :normal
    end
  end
end

app/controllers/api/v2/boards_controller.rb
class Api::V2::BoardsController < ApplicationController
  def index 
    @boards = Board.all
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only: %i[favorite show edit update destroy hide]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @boards = Board.normal.page(params[:page]).per(2)
  end

  def show
    @posts = @board.posts.includes(:user)
  end

  def favorite
    current_user.toggle_favorite_board(@board)

    respond_to do |format|
      format.html { redirect_to favorites_path, notice: '更新我的最愛成功!' }
      format.json do
        render json: { status: @board.favorited_by?(current_user) }
      end
    end
  end

  def new
    @board = Board.new
    authorize @board, :new?
  end

  def create
    @board = current_user.boards.create(board_params)
    @board.users << current_user
    authorize @board, :create?

    if @board.save
      redirect_to boards_path, notice: '新增成功！！'
    else
      render :new, notice: 'errror'
    end
  end

  def edit; end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: '更新成功'
    else
      render :edit, notice: 'error'
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: '刪除成功'
  end

  def hide
    @board.hide! if @board.may_hide?
    redirect_to boards_path, notice: '看版己隱藏'
  end

  private

  def find_board
    @board = Board.normal.find(params[:id])
  end

  def board_params
    #strong parameters
    params.require(:board).permit(:title, :intro)
  end
end

app/helpers/api/v2/boards_helper.rb
module Api::V2::BoardsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def display_bm(board)
    if board.users.count > 0
      return board.users.map { |user| user.account }.join(" / ")
    else
      return "徵求中"
    end
  end
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
    <% board.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(board) do |f| %> 
  <div class="form-group">
    <%= f.label :title, "看板名稱" %>
    <%= f.text_field :title, class: "form-control" %> 
  </div>

  <div class="form-group">
    <%= f.label :intro, "看板說明" %> 
    <%= f.text_area:intro, class: "form-control" %> 
  </div>

  <%= f.submit "送出", class: "btn btn-primary" %> 
<% end %>

app/views/boards/edit.html.erb
<div class="container">
  <h1>編輯看板</h1>

  <%= render 'form', board: @board %>
</div>

app/views/boards/index.html.erb
<h1>看板</h1>

<div id="board">
  <Board></Board>
</div>

<% if policy(:board).create? %>
  <%= link_to "新增看版", new_board_path %>
<% end %>

<table class="table">
  <thead>
    <th>版名</th>
    <th>link</th>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
    <tr>
      <td>
        <%= link_to board.title, board_path(board) %>
      </td>
      <td>
        <%= link_to "編輯", edit_board_path(board) %>
        <%= link_to "刪除", board_path(board), method: :delete, data: {confirm: "確認刪除？"} %>
        <%= link_to  "隱版", hide_board_path(board), method: :put %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

app/views/boards/new.html.erb
<div class="container">
  <h1>新增看板</h1>

  <%= render 'form', board: @board %>
</div>

app/views/boards/show.html.erb
<h1 data-controller="heart" data-heart-id="<%= @board.id %>">
  看板 <%= @board.title %>
  <a data-action="click -> heart#favorite">
    <% if @board.favorited_by?(current_user) %>
      <i class="fas fa-heart" data-target="heart.heart"></i>
    <% else %>
      <i class="far fa-heart" data-target="heart.heart"></i>
    <% end %>
  </a>
</h1>

<p>
  [ 版主：<%= display_bm(@board) %> ]
</p>

<div>
  <%= link_to "new Post", new_board_post_path(@board) %>
</div>

<ul>
  <% @posts.each do |post| %>
    <li>
      [<%= post.display_username %>]
      <%= link_to post.title, post_path(post) %>
      <%= link_to  "編輯", edit_post_path(post) %>
    </li>
  <% end %>
</ul>

<%= link_to "Board Index", boards_path %>