config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/index', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/pricing', to: 'pages#pricing'
  get '/payment', to: 'pages#payment'
  post '/checkout', to: 'pages#checkout'

  #API
  namespace :api do
    namespace :v2 do
      resources :boards, only: %i[index]
    end
  end

  #Origin
  resources :favorites, only: %i[index]

  resources :boards do
    resources :posts, shallow: true do
      resources :comments, shallow: true, only: %i[create]
    end

    member do
      post :favorite
      put :hide
    end
  end

  # shallow =>
  # resources :boards do
  #   resources :posts, only: [:index, :new, :create]
  # end
  # resources :posts, except: [:index, :new, :create]

  resources :users, only: %i[create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid

  validates :title, presence: true
  validates :serial, uniqueness: true

  belongs_to :board
  belongs_to :user 
  has_many :comments
  has_one_attached :photo
  has_rich_text :hello

  before_create :create_serial
  #只有新增資料時執行

  def display_username
    if user.nil? 
      "-"
    else
      user.account
    end
  end

  private 

  def create_serial
    self.serial = serial_generator(10)
  end

  def serial_generator(n)
    list = [*'A'..'Z', *'a'..'z', *0..9]
    list -= ['i','l','I',1,0,'o']
    list.sample(n).join
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_board, only: [:new, :create]
  before_action :authenticate_user!, except: [:show]

  def show 
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @comment = @post.comments.new
  end

  def new
    @post = @board.posts.new
  end

  def create
    @post = @board.posts.new(post_params)

    if @post.save
      #寄信
      SendmailJob.set(wait: 10.second).perform_later(@post)
      redirect_to @board, notice: '文章新增成功'
    else
      render :new
    end
  end

  def edit 
    @post = current_user.posts.find(params[:id])
  end
  
  def update 
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: '文章更新成功'
    else
      render :edit 
    end
  end

  private 
  
  def post_params
    params.require(:post).permit(:title, :content, :photo, :hello).merge(user: current_user)
  end

  def find_board
    @board = Board.find(params[:board_id])
  end
end

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <ul>
    <% post.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: post, url: board_posts_path, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :hello %>
    <%= f.rich_text_area :hello, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.submit "Create Post", class: "btn btn-primary" %> 
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>編輯文章</h1>

<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @post, local: true) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.submit "Create Post" %> 
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>new post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<ul>
  <li>
    <span>作者</span>
    <span><%= @post.user.account %></span>
  </li>
  <li>
    <span>標題</span>
    <span><%= @post.title %></span>
  </li>
  <li>
    <span>時間</span>
    <span><%= @post.created_at %></span>
  </li>
</ul>


<p>
  <%= @post.content %>
  <br>
  <%= @post.hello %>
  <br>
  <%= image_tag @post.photo.variant(resize_to_limit: [100, 100]) if @post.photo.attached? %>
</p>

<hr>

<%= form_with(model: @comment, url: post_comments_path(@post), class: "form-inline") do |f| %>
  <div class="form-group">
    <%= f.text_field :content, class: "form-control" %>
  </div>

  <%= f.submit "送出", class: "btn btn-primary ml-2" %>
<% end %>

<hr>

<ul>
  <h3>----All post comments----</h3>
  <% @comments.each do |comment| %>
    <li>
      <%= comment.user.account %> :
      <%= comment.content %>
    </li>
  <% end %>
</ul>